<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
      <PackageReference Include="Ninject" Version="3.3.4" />
      <PackageReference Include="Ninject.Extensions.Factory" Version="3.3.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebShop.BLL\WebShop.BLL.csproj" />
      <ProjectReference Include="..\WebShop.DAL\WebShop.DAL.csproj" />
    </ItemGroup>

</Project>
